language: java

jdk:
  - oraclejdk8

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1fe81fd08dfc36899d78
    on_success: change
    on_failure: always
    on_start: never

sudo: required

dist: trusty

cache:
  directories:
    - $HOME/.m2
